#consumer
spring:
  profiles: dev
  application:
    name: cloud-k8s-consumer
  cloud:
    nacos:
      server-addr: 10.10.20.90:8848
  main:
    allow-bean-definition-overriding:  true
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#  sleuth:
#    sampler:
#      probability: 1

server:
  port: 8080