#consumer
spring:
  profiles: dev
  application:
    name: cloud-k8s-consumer
  cloud:
    nacos:
      server-addr: 10.10.20.90:8848
  main:
    allow-bean-definition-overriding:  true

server:
  port: 8080