#sms
server:
  port: 8082
spring:
  profiles: dev
  application:
    name: cloud-k8s-sms
  cloud:
    nacos:
      discovery:
        server-addr: 10.10.20.90:8848
  # zipkin:
 #   base-url: http://127.0.0.1:9411/
 # sleuth:
 #   sampler:
 #     probability: 1
biz:
  ca: ca1.txt