#cloud-k8s-producer
spring:
  profiles: dev
  application:
    name: cloud-k8s-producer
  cloud:
    nacos:
      server-addr: 10.10.20.90:8848
#  zipkin:
#    base-url: http://127.0.0.1:9411/
#  sleuth:
#    sampler:
#      probability: 1
server:
  port: 8081