#cloud-k8s-gateway
spring:
  profiles: dev
  application:
    name: cloud-k8s-gateway
  cloud:
    nacos:
      discovery:
        server-addr: nacos-headless.default.svc.cluster.local:8848
    gateway:
      routes:
        - id: consumer
          uri: lb://cloud-k8s-consumer
          predicates:
            - Path=/api-consumer/**
          filters:
            - StripPrefix=1

server:
  port: 8079
